### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 'mydb.permissions.name' isn't in GROUP BY

### ISSUE THREAD

**Issue by drallan** [GeniusTS/roles#1]
Using MySQL version: 5.5.47-0+deb8u1-log (Debian)

**Comment by aboudeh87** [comment]
Can you tell me when this error appear?

**Comment by drallan** [comment]
Using Auth::user()->can('blah')
Full error : 
SQLSTATE[42000]: Syntax error or access violation: 1055 'mydb.permissions.name' isn't in GROUP BY (SQL: select `permissions`.*, `permission_role`.`created_at` as `pivot_created_at`, `permission_role`.`updated_at` as `pivot_updated_at` from `permissions` inner join `permission_role` on `permission_role`.`permission_id` = `permissions`.`id` inner join `roles` on `roles`.`id` = `permission_role`.`role_id` where 0 = 1 or `roles`.`level` < 0 group by `permissions`.`id`, `pivot_created_at`, `pivot_updated_at`)

**Comment by aboudeh87** [comment]
This issue appear when the sql mode set to "ONLY_FULL_GROUP_BY", update the package it should work now

**Comment by drallan** [comment]
Thanks so much
