### ISSUE TITLE
Error attachRole

### ISSUE THREAD

**Issue by nguyenvuvn** [GeniusTS/roles#2]
Help me!
I use method attachRole with  error:

BadMethodCallException in Builder.php line 2440:
Call to undefined method Illuminate\Database\Query\Builder::attach()

**Comment by aboudeh87** [comment]
did you attach the HasRoleAndPermission trait to your model?

**Comment by nguyenvuvn** [comment]
I used HasRoleAndPermission trait. I use uuid primary key. Thanks!

**Comment by aboudeh87** [comment]
So the problem resolved?
